// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authorizedkeys

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthorizedKeys creates a new instance of MockAuthorizedKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorizedKeys(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorizedKeys {
	mock := &MockAuthorizedKeys{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorizedKeys is an autogenerated mock type for the AuthorizedKeys type
type MockAuthorizedKeys struct {
	mock.Mock
}

type MockAuthorizedKeys_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizedKeys) EXPECT() *MockAuthorizedKeys_Expecter {
	return &MockAuthorizedKeys_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockAuthorizedKeys
func (_mock *MockAuthorizedKeys) Get(ctx context.Context, opts GetOptions) []string {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(context.Context, GetOptions) []string); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockAuthorizedKeys_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAuthorizedKeys_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - opts GetOptions
func (_e *MockAuthorizedKeys_Expecter) Get(ctx interface{}, opts interface{}) *MockAuthorizedKeys_Get_Call {
	return &MockAuthorizedKeys_Get_Call{Call: _e.mock.On("Get", ctx, opts)}
}

func (_c *MockAuthorizedKeys_Get_Call) Run(run func(ctx context.Context, opts GetOptions)) *MockAuthorizedKeys_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 GetOptions
		if args[1] != nil {
			arg1 = args[1].(GetOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorizedKeys_Get_Call) Return(strings []string) *MockAuthorizedKeys_Get_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockAuthorizedKeys_Get_Call) RunAndReturn(run func(ctx context.Context, opts GetOptions) []string) *MockAuthorizedKeys_Get_Call {
	_c.Call.Return(run)
	return _c
}
