// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package imds

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/feature/ec2/imds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImdsClient creates a new instance of MockImdsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImdsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImdsClient {
	mock := &MockImdsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImdsClient is an autogenerated mock type for the ImdsClient type
type MockImdsClient struct {
	mock.Mock
}

type MockImdsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImdsClient) EXPECT() *MockImdsClient_Expecter {
	return &MockImdsClient_Expecter{mock: &_m.Mock}
}

// GetDynamicData provides a mock function for the type MockImdsClient
func (_mock *MockImdsClient) GetDynamicData(ctx context.Context, params *imds.GetDynamicDataInput, optFns ...func(*imds.Options)) (*imds.GetDynamicDataOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetDynamicData")
	}

	var r0 *imds.GetDynamicDataOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetDynamicDataInput, ...func(*imds.Options)) (*imds.GetDynamicDataOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetDynamicDataInput, ...func(*imds.Options)) *imds.GetDynamicDataOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imds.GetDynamicDataOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *imds.GetDynamicDataInput, ...func(*imds.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImdsClient_GetDynamicData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDynamicData'
type MockImdsClient_GetDynamicData_Call struct {
	*mock.Call
}

// GetDynamicData is a helper method to define mock.On call
//   - ctx context.Context
//   - params *imds.GetDynamicDataInput
//   - optFns ...func(*imds.Options)
func (_e *MockImdsClient_Expecter) GetDynamicData(ctx interface{}, params interface{}, optFns ...interface{}) *MockImdsClient_GetDynamicData_Call {
	return &MockImdsClient_GetDynamicData_Call{Call: _e.mock.On("GetDynamicData",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockImdsClient_GetDynamicData_Call) Run(run func(ctx context.Context, params *imds.GetDynamicDataInput, optFns ...func(*imds.Options))) *MockImdsClient_GetDynamicData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *imds.GetDynamicDataInput
		if args[1] != nil {
			arg1 = args[1].(*imds.GetDynamicDataInput)
		}
		var arg2 []func(*imds.Options)
		var variadicArgs []func(*imds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*imds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockImdsClient_GetDynamicData_Call) Return(getDynamicDataOutput *imds.GetDynamicDataOutput, err error) *MockImdsClient_GetDynamicData_Call {
	_c.Call.Return(getDynamicDataOutput, err)
	return _c
}

func (_c *MockImdsClient_GetDynamicData_Call) RunAndReturn(run func(ctx context.Context, params *imds.GetDynamicDataInput, optFns ...func(*imds.Options)) (*imds.GetDynamicDataOutput, error)) *MockImdsClient_GetDynamicData_Call {
	_c.Call.Return(run)
	return _c
}

// GetIAMInfo provides a mock function for the type MockImdsClient
func (_mock *MockImdsClient) GetIAMInfo(ctx context.Context, params *imds.GetIAMInfoInput, optFns ...func(*imds.Options)) (*imds.GetIAMInfoOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetIAMInfo")
	}

	var r0 *imds.GetIAMInfoOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetIAMInfoInput, ...func(*imds.Options)) (*imds.GetIAMInfoOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetIAMInfoInput, ...func(*imds.Options)) *imds.GetIAMInfoOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imds.GetIAMInfoOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *imds.GetIAMInfoInput, ...func(*imds.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImdsClient_GetIAMInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIAMInfo'
type MockImdsClient_GetIAMInfo_Call struct {
	*mock.Call
}

// GetIAMInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - params *imds.GetIAMInfoInput
//   - optFns ...func(*imds.Options)
func (_e *MockImdsClient_Expecter) GetIAMInfo(ctx interface{}, params interface{}, optFns ...interface{}) *MockImdsClient_GetIAMInfo_Call {
	return &MockImdsClient_GetIAMInfo_Call{Call: _e.mock.On("GetIAMInfo",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockImdsClient_GetIAMInfo_Call) Run(run func(ctx context.Context, params *imds.GetIAMInfoInput, optFns ...func(*imds.Options))) *MockImdsClient_GetIAMInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *imds.GetIAMInfoInput
		if args[1] != nil {
			arg1 = args[1].(*imds.GetIAMInfoInput)
		}
		var arg2 []func(*imds.Options)
		var variadicArgs []func(*imds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*imds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockImdsClient_GetIAMInfo_Call) Return(getIAMInfoOutput *imds.GetIAMInfoOutput, err error) *MockImdsClient_GetIAMInfo_Call {
	_c.Call.Return(getIAMInfoOutput, err)
	return _c
}

func (_c *MockImdsClient_GetIAMInfo_Call) RunAndReturn(run func(ctx context.Context, params *imds.GetIAMInfoInput, optFns ...func(*imds.Options)) (*imds.GetIAMInfoOutput, error)) *MockImdsClient_GetIAMInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstanceIdentityDocument provides a mock function for the type MockImdsClient
func (_mock *MockImdsClient) GetInstanceIdentityDocument(ctx context.Context, params *imds.GetInstanceIdentityDocumentInput, optFns ...func(*imds.Options)) (*imds.GetInstanceIdentityDocumentOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetInstanceIdentityDocument")
	}

	var r0 *imds.GetInstanceIdentityDocumentOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetInstanceIdentityDocumentInput, ...func(*imds.Options)) (*imds.GetInstanceIdentityDocumentOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetInstanceIdentityDocumentInput, ...func(*imds.Options)) *imds.GetInstanceIdentityDocumentOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imds.GetInstanceIdentityDocumentOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *imds.GetInstanceIdentityDocumentInput, ...func(*imds.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImdsClient_GetInstanceIdentityDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstanceIdentityDocument'
type MockImdsClient_GetInstanceIdentityDocument_Call struct {
	*mock.Call
}

// GetInstanceIdentityDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - params *imds.GetInstanceIdentityDocumentInput
//   - optFns ...func(*imds.Options)
func (_e *MockImdsClient_Expecter) GetInstanceIdentityDocument(ctx interface{}, params interface{}, optFns ...interface{}) *MockImdsClient_GetInstanceIdentityDocument_Call {
	return &MockImdsClient_GetInstanceIdentityDocument_Call{Call: _e.mock.On("GetInstanceIdentityDocument",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockImdsClient_GetInstanceIdentityDocument_Call) Run(run func(ctx context.Context, params *imds.GetInstanceIdentityDocumentInput, optFns ...func(*imds.Options))) *MockImdsClient_GetInstanceIdentityDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *imds.GetInstanceIdentityDocumentInput
		if args[1] != nil {
			arg1 = args[1].(*imds.GetInstanceIdentityDocumentInput)
		}
		var arg2 []func(*imds.Options)
		var variadicArgs []func(*imds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*imds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockImdsClient_GetInstanceIdentityDocument_Call) Return(getInstanceIdentityDocumentOutput *imds.GetInstanceIdentityDocumentOutput, err error) *MockImdsClient_GetInstanceIdentityDocument_Call {
	_c.Call.Return(getInstanceIdentityDocumentOutput, err)
	return _c
}

func (_c *MockImdsClient_GetInstanceIdentityDocument_Call) RunAndReturn(run func(ctx context.Context, params *imds.GetInstanceIdentityDocumentInput, optFns ...func(*imds.Options)) (*imds.GetInstanceIdentityDocumentOutput, error)) *MockImdsClient_GetInstanceIdentityDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function for the type MockImdsClient
func (_mock *MockImdsClient) GetMetadata(ctx context.Context, params *imds.GetMetadataInput, optFns ...func(*imds.Options)) (*imds.GetMetadataOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *imds.GetMetadataOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetMetadataInput, ...func(*imds.Options)) (*imds.GetMetadataOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetMetadataInput, ...func(*imds.Options)) *imds.GetMetadataOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imds.GetMetadataOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *imds.GetMetadataInput, ...func(*imds.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImdsClient_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type MockImdsClient_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - params *imds.GetMetadataInput
//   - optFns ...func(*imds.Options)
func (_e *MockImdsClient_Expecter) GetMetadata(ctx interface{}, params interface{}, optFns ...interface{}) *MockImdsClient_GetMetadata_Call {
	return &MockImdsClient_GetMetadata_Call{Call: _e.mock.On("GetMetadata",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockImdsClient_GetMetadata_Call) Run(run func(ctx context.Context, params *imds.GetMetadataInput, optFns ...func(*imds.Options))) *MockImdsClient_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *imds.GetMetadataInput
		if args[1] != nil {
			arg1 = args[1].(*imds.GetMetadataInput)
		}
		var arg2 []func(*imds.Options)
		var variadicArgs []func(*imds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*imds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockImdsClient_GetMetadata_Call) Return(getMetadataOutput *imds.GetMetadataOutput, err error) *MockImdsClient_GetMetadata_Call {
	_c.Call.Return(getMetadataOutput, err)
	return _c
}

func (_c *MockImdsClient_GetMetadata_Call) RunAndReturn(run func(ctx context.Context, params *imds.GetMetadataInput, optFns ...func(*imds.Options)) (*imds.GetMetadataOutput, error)) *MockImdsClient_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegion provides a mock function for the type MockImdsClient
func (_mock *MockImdsClient) GetRegion(ctx context.Context, params *imds.GetRegionInput, optFns ...func(*imds.Options)) (*imds.GetRegionOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetRegion")
	}

	var r0 *imds.GetRegionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetRegionInput, ...func(*imds.Options)) (*imds.GetRegionOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetRegionInput, ...func(*imds.Options)) *imds.GetRegionOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imds.GetRegionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *imds.GetRegionInput, ...func(*imds.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImdsClient_GetRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegion'
type MockImdsClient_GetRegion_Call struct {
	*mock.Call
}

// GetRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - params *imds.GetRegionInput
//   - optFns ...func(*imds.Options)
func (_e *MockImdsClient_Expecter) GetRegion(ctx interface{}, params interface{}, optFns ...interface{}) *MockImdsClient_GetRegion_Call {
	return &MockImdsClient_GetRegion_Call{Call: _e.mock.On("GetRegion",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockImdsClient_GetRegion_Call) Run(run func(ctx context.Context, params *imds.GetRegionInput, optFns ...func(*imds.Options))) *MockImdsClient_GetRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *imds.GetRegionInput
		if args[1] != nil {
			arg1 = args[1].(*imds.GetRegionInput)
		}
		var arg2 []func(*imds.Options)
		var variadicArgs []func(*imds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*imds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockImdsClient_GetRegion_Call) Return(getRegionOutput *imds.GetRegionOutput, err error) *MockImdsClient_GetRegion_Call {
	_c.Call.Return(getRegionOutput, err)
	return _c
}

func (_c *MockImdsClient_GetRegion_Call) RunAndReturn(run func(ctx context.Context, params *imds.GetRegionInput, optFns ...func(*imds.Options)) (*imds.GetRegionOutput, error)) *MockImdsClient_GetRegion_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserData provides a mock function for the type MockImdsClient
func (_mock *MockImdsClient) GetUserData(ctx context.Context, params *imds.GetUserDataInput, optFns ...func(*imds.Options)) (*imds.GetUserDataOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetUserData")
	}

	var r0 *imds.GetUserDataOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetUserDataInput, ...func(*imds.Options)) (*imds.GetUserDataOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *imds.GetUserDataInput, ...func(*imds.Options)) *imds.GetUserDataOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imds.GetUserDataOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *imds.GetUserDataInput, ...func(*imds.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImdsClient_GetUserData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserData'
type MockImdsClient_GetUserData_Call struct {
	*mock.Call
}

// GetUserData is a helper method to define mock.On call
//   - ctx context.Context
//   - params *imds.GetUserDataInput
//   - optFns ...func(*imds.Options)
func (_e *MockImdsClient_Expecter) GetUserData(ctx interface{}, params interface{}, optFns ...interface{}) *MockImdsClient_GetUserData_Call {
	return &MockImdsClient_GetUserData_Call{Call: _e.mock.On("GetUserData",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockImdsClient_GetUserData_Call) Run(run func(ctx context.Context, params *imds.GetUserDataInput, optFns ...func(*imds.Options))) *MockImdsClient_GetUserData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *imds.GetUserDataInput
		if args[1] != nil {
			arg1 = args[1].(*imds.GetUserDataInput)
		}
		var arg2 []func(*imds.Options)
		var variadicArgs []func(*imds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*imds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockImdsClient_GetUserData_Call) Return(getUserDataOutput *imds.GetUserDataOutput, err error) *MockImdsClient_GetUserData_Call {
	_c.Call.Return(getUserDataOutput, err)
	return _c
}

func (_c *MockImdsClient_GetUserData_Call) RunAndReturn(run func(ctx context.Context, params *imds.GetUserDataInput, optFns ...func(*imds.Options)) (*imds.GetUserDataOutput, error)) *MockImdsClient_GetUserData_Call {
	_c.Call.Return(run)
	return _c
}
